name: Update Skills Table

on:
  schedule:
    - cron: "0 0 * * *"   # runs daily at midnight
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-skills:
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.GH_PAT }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run update script
        run: node update-readme.js

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/RudrasenaReddy87/RudrasenaReddy87.git
          git fetch origin main
          git reset --hard origin/main
          git add README.md
          git diff --cached --quiet || git commit -m "Auto-update skills table"
          git push
