name: Update Skills Table

on:
  schedule:
    - cron: "0 0 * * *"  # daily at midnight
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-skills:
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.GH_PAT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        run: python update_skills.py

      - name: Commit and Push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git fetch origin main
          git checkout main
          git reset --hard origin/main
          git add README.md
          git diff --cached --quiet || git commit -m "Auto-update skills table"
          git push origin main --force-with-lease
